version: '2'
services:
  zookeeper:
    image: hexagram30/zookeeper:3.4.11
    ports:
      - "2181:2181"
  kafka:
    image: hexagram30/kafka:2.12-1.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
