version: '2'
services:
  zookeeper:
    image: hexagram30/zookeeper:3.4.11
    ports:
      - "2181:2181"
  kafka:
    depends_on:
      - "zookeeper"
    image: hexagram30/kafka:2.12-1.0.1
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    command: sh -c 'wait-for.sh zookeeper:2181 -- start-kafka.sh'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
